// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Example
{

    internal class Notify
    {

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("strike")]
        public string Strike { get; set; }
    }

}
