// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Example
{

    internal class Status
    {

        [JsonProperty("lr")]
        public int Lr { get; set; }

        [JsonProperty("notify")]
        public Notify Notify { get; set; }

        [JsonProperty("notificationsRead")]
        public object[] NotificationsRead { get; set; }

        [JsonProperty("invites")]
        public int Invites { get; set; }

        [JsonProperty("share")]
        public string Share { get; set; }

        [JsonProperty("default_board")]
        public int DefaultBoard { get; set; }
    }

}
