// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Example
{

    internal class User
    {

        [JsonProperty("user_id")]
        public int UserId { get; set; }

        [JsonProperty("username")]
        public string Username { get; set; }

        [JsonProperty("urlname")]
        public string Urlname { get; set; }

        [JsonProperty("created_at")]
        public int CreatedAt { get; set; }

        [JsonProperty("avatar")]
        public Avatar Avatar { get; set; }

        [JsonProperty("extra")]
        public object Extra { get; set; }

        [JsonProperty("board_count")]
        public int BoardCount { get; set; }

        [JsonProperty("like_count")]
        public int LikeCount { get; set; }

        [JsonProperty("follower_count")]
        public int FollowerCount { get; set; }

        [JsonProperty("commodity_count")]
        public int CommodityCount { get; set; }

        [JsonProperty("boards_like_count")]
        public int BoardsLikeCount { get; set; }

        [JsonProperty("pin_count")]
        public int PinCount { get; set; }

        [JsonProperty("creations_count")]
        public int CreationsCount { get; set; }

        [JsonProperty("explore_following_count")]
        public int ExploreFollowingCount { get; set; }

        [JsonProperty("following_count")]
        public int FollowingCount { get; set; }

        [JsonProperty("profile")]
        public Profile Profile { get; set; }

        [JsonProperty("status")]
        public Status Status { get; set; }
    }

}
