// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Senparc.Weixin.MP.Sample.CommonService.JuHeAPI.Model
{

    internal class Datum
    {

        [JsonProperty("content")]
        public string Content { get; set; }

        [JsonProperty("hashId")]
        public string HashId { get; set; }

        [JsonProperty("unixtime")]
        public int Unixtime { get; set; }

        [JsonProperty("updatetime")]
        public string Updatetime { get; set; }


        [JsonProperty("url")]
        public string Url { get; set; }
    }

}
