// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Senparc.Weixin.MP.Sample.CommonService.JuHeAPI.Model
{

    internal class XiaoHuaResponse
    {


        [JsonProperty("reason")]
        public string Reason { get; set; }

        [JsonProperty("result")]
        public Datum[] Result { get; set; }

        [JsonProperty("error_code")]
        public int ErrorCode { get; set; }
    }

}
